TestBank.Web/Controllers/AnswersController.cs
#region using..
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestBank.Entity.Model;
using TestBank.Web.Models;
using TestBank.Web.ViewModels;
using TestBank.Web.Infrastructure.ServiceProxy;
using TestBank.Web.Infrastructure.AutoMapper;
using AutoMapper;
using PagedList;
using TestBank.Entity.Utilities;
using NLog;
using TestBank.Web.Infrastructure.Attributes;
using TestBank.Web.Infrastructure.Utilities;
using TestBank.Entity.ErrorHandler;
using System.IO;
using TestBank.Entity.Models;
using TestBank.Web.Filters;
using TestBank.Web.Infrastructure.Encryption;
#endregion

namespace TestBank.Web.Controllers
{
    public class AnswersController : BaseController
    {
        Logger logger = LogManager.GetCurrentClassLogger();
        private const string clienSecret = "&*@Pc43fass%wTr5!4ord";

        public ViewResult Results(int testId)
        {
            var urlParams = new List<Tuple<string, string>>();
            urlParams.Add(new Tuple<string, string>("testId", testId.ToString()));

            var listAnswers = TestBankApiProxy.Get<List<UserAnswer>>(ApiKey,ResourceEndPoint.UserAnswers_All, urlParams);
            IEnumerable<UserAnswersResultViewModel> model = null;
            if (listAnswers != null)
            {
                model = Mapper.Map<IEnumerable<UserAnswer>, IEnumerable<UserAnswersResultViewModel>>(listAnswers);
            }
            return View(model);
        }

        [AllowAnonymous]
        //[CryptoValueProvider]
        public ActionResult Start(int testId)
        {
            if (testId == 0)
            {
                throw new Exception("invalid test id.");
            }

            if (Request.IsAuthenticated)
            {
                SetUserIdentity(User.Identity.Name);
                return AddAnswersAndRedirect(testId);
            }
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        //[CryptoValueProvider]
        public ActionResult Start(int testId, UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                if (testId > 0 && userViewModel != null)
                {
                    var user = Mapper.Map<UserViewModel, User>(userViewModel);
                    user.Role = Roles.Student;
                    try
                    {
                        user = TestBankApiProxy.Post<User>(ApiKey, user, ResourceEndPoint.User_Post);
                    }
                    catch (ApiError error)
                    {
                        if (error.Errors != null)
                        {
                            foreach (var item in error.Errors)
                            {
                                ModelState.AddModelError("", item);
                            }
                        }
                        else
                            ModelState.AddModelError("", error.Message);
                        
                        return View();
                    }
                    
                    if (user !=  null)
                    {
                        if (!Request.IsAuthenticated)
                        {
                            ApiKey = TestBankApiProxy.Authenticate(new Credentials() { User = user.Id, Password = "password" });
                            SetUserIdentity(user.Id);
                            return AddAnswersAndRedirect(testId);
                        }
                    }
                }
            }
            return View();
        }

        [AllowAnonymous]
        //[CryptoValueProvider]
        public ActionResult Save(int testId, int? responseId, int? page)
        {
            if (testId == 0)
            {
                throw new Exception("invalid test id.");
            }
            if (responseId.HasValue && responseId.Value == 0)
            {
                throw new Exception("invalid response Id.");
            }
            if (Session["secret"] == null)
            {
                return RedirectToAction("Start", new { testId = EncryptDecryptQueryString.Encrypt(testId.ToString()) });
            }
            return GetAnswerViewModel(testId, responseId, page);
        }

        [AllowAnonymous] 
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Save")]
        public ActionResult Save(UserAnswersInputViewModel ansInputModel)
        {
            ClearModelState();
            if (!(ValidateUserIdentity(ansInputModel.UserId)))
            {
                return View("Unauthorized");
            }
            
            var answers = SaveAnswer(ansInputModel);
            return GetAnswerViewModel(ansInputModel.AssessmentId, ansInputModel.Id, ansInputModel.CurrentPageId);
        }

        [AllowAnonymous]
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Save & Next")]
        public ActionResult SaveNext(UserAnswersInputViewModel ansInputModel)
        {
            ClearModelState();
            if (!(ValidateUserIdentity(ansInputModel.UserId)))
            {
                return View("Unauthorized");
            }
            var answers = SaveAnswer(ansInputModel);
            
            if (answers != null)
            {
                return GetAnswerViewModel(ansInputModel.AssessmentId, ansInputModel.Id, ansInputModel.CurrentPageId + 1);
            }
            else
            {
                return GetAnswerViewModel(ansInputModel.AssessmentId, ansInputModel.Id, ansInputModel.CurrentPageId);
            }

        }

        [AllowAnonymous]
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Finish")] 
        public ActionResult Finish(UserAnswersInputViewModel ansInputModel)
        {
            if (!(ValidateUserIdentity(ansInputModel.UserId)))
            {
                return View("Unauthorized");
            }
            ansInputModel.IsTestCompleted = true;
            var answers = SaveAnswer(ansInputModel);
            if (answers == null)
            {
                ClearModelState();
                return GetAnswerViewModel(ansInputModel.AssessmentId, ansInputModel.Id, ansInputModel.CurrentPageId);
            }
            
            return RedirectToAction("Finish", new { testId = EncryptDecryptQueryString.Encrypt(ansInputModel.AssessmentId.ToString()) });
        }

        [AllowAnonymous]
        [HttpGet]
        //[CryptoValueProvider]
        public ActionResult Finish(int testId)
        {
            return View("Finish");
        }


        public ActionResult Export(int testId, string output)
        {
            //api/UserAnswers/Export?testId=9&output=Excel
            var urlParams = new List<Tuple<string, string>>();
            urlParams.Add(new Tuple<string, string>("testId", testId.ToString()));
            urlParams.Add(new Tuple<string, string>("output", output));
            var exportOutput = TestBankApiProxy.DownloadFile(ApiKey,"api/UserAnswers/Export?testId={testId}&output={output}", urlParams);

            Stream report = new MemoryStream(exportOutput);
            return new FileStreamResult(report, "application/ms-excel")
            {
                FileDownloadName = string.Format("TestResults_{0:yyyyMMddHHmmss}.xlsx",DateTime.Now)
            };
        }

        #region Private Methods
        private ViewResult GetAnswerViewModel(int id, int? responseId, int? page)
        {
            logger.Debug("get answer details");
            int pageSize = 4;
            page = page ?? 1;
            int pageIndex = page.Value == 0 ? 1 : page.Value;

            UserAnswersInputViewModel answerModel = null;
            UserAnswer answer = null;
            if (responseId.HasValue && responseId.Value > 0)
            {
                logger.Debug("response id = {0}", responseId.Value);
                answer = TestBankApiProxy.Get<UserAnswer>(ApiKey, ResourceEndPoint.UserAnswers_Get, responseId.Value);
                logger.Debug("Answer id = {0}, testid = {1}", answer.Id, answer.AssessmentId);
                answerModel = answer.MapTo<UserAnswersInputViewModel>();

                if (!(ValidateUserIdentity(answerModel.UserId)))
                {
                    return View("Unauthorized");
                }
            }
            else
            {
                //if (!(ValidateUserIdentity(answerModel.UserId)))
                //{
                //    return View("Unauthorized");
                //}
            }
            var assessment = GetAssessmentDetails(id, pageIndex, pageSize);

            if (answerModel != null && assessment != null && answer != null)
            {
                int i = (pageIndex - 1) * pageSize;
                var mappedQuestions = (from q in assessment.QuestionDetails
                                       select new UserAnswersInputViewModel.AnswerInputViewModel()
                                       {
                                           QuestionId = Convert.ToInt32(q.Id),
                                           Description = q.Description,
                                           Nr = ++i,
                                           OptionItems = q.Options.Select(x => new SelectListItem
                                           {
                                               Text = x.Text,
                                               Value = x.Id,
                                               Selected = (x.Id == answer.Answers.Where(o => o.Question.QuestionId == q.Id).DefaultIfEmpty(new UserAnswer.Answer()).FirstOrDefault().SelectedOption)
                                           }
                                               ).ToList(),
                                       }).ToList();

                answerModel.QuestionAnswers = mappedQuestions;

TestBank.Web/Controllers/AssessmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestBank.Entity.Model;
using TestBank.Web.Models;
using TestBank.Web.Infrastructure.ServiceProxy;
using TestBank.Web.ViewModels;
using AutoMapper;
using TestBank.Web.Infrastructure.AutoMapper.Profiles.Resolvers;
using TestBank.Entity.Utilities;
using System.Configuration;

namespace TestBank.Web.Controllers
{   
    public class AssessmentsController : BaseController
    {
        

        //
        // GET: /Assessments/

        public ViewResult Index(int? page)
        {
            var listAssessments = TestBankApiProxy.Get<List<Assessment>>(ApiKey, ResourceEndPoint.Assessments_All);
            IEnumerable<AssessmentViewModel> model = null;
            if (listAssessments != null)
            {
                model = Mapper.Map<IEnumerable<Assessment>, IEnumerable<AssessmentViewModel>>(listAssessments);
            }
            return View(model);
        }

        //
        // GET: /Assessments/Details/5

        public ViewResult Details(int id)
        {
            var assessment = TestBankApiProxy.Get<Assessment>(ApiKey, ResourceEndPoint.Assessments_Get, id);
            AssessmentViewModel assessmentViewModel = null;
            if (assessment != null)
            {
                assessmentViewModel = Mapper.Map<Assessment, AssessmentViewModel>(assessment);
            }
            return View(assessmentViewModel);
        }

        //
        // GET: /Assessments/Create

        public ActionResult Create()
        {
            var assessmentviewmodel = new AssessmentViewModel();
            GetAssessmentData(assessmentviewmodel);
            return View(assessmentviewmodel);
        }

        private void GetAssessmentData(AssessmentViewModel assessmentviewmodel)
        {
            assessmentviewmodel.AllQuestions = new List<QuestionReferenceViewModel>();
            var allQuestions = GetAllQuestions();
            assessmentviewmodel.AllQuestions.AddRange(allQuestions);
            assessmentviewmodel.AllQuestionIds = allQuestions.Select(q => q.QuestionId).ToArray();
        }

        //
        // POST: /Assessments/Create

        [HttpPost]
        public ActionResult Create(AssessmentViewModel assessmentViewModel)
        {
            if (ModelState.IsValid)
            {
                if (assessmentViewModel != null)
                {
                    assessmentViewModel.Link = string.Format("{0}Answers/Start?testId={{id}}", ConfigurationManager.AppSettings.Get("AppHostUrl"));
                    assessmentViewModel.Questions = assessmentViewModel.QuestionIds.Select(x => new QuestionReferenceViewModel { QuestionId = x }).ToList();
                    var assessment = Mapper.Map<AssessmentViewModel, Assessment>(assessmentViewModel);
                    assessment = TestBankApiProxy.Post<Assessment>(ApiKey, assessment, ResourceEndPoint.Assessments_Post);
                }

                return RedirectToAction("Index");
            }

            GetAssessmentData(assessmentViewModel);
            return View(assessmentViewModel);
        }

        //
        // GET: /Assessments/Edit/5

        public ActionResult Edit(int id)
        {
            AssessmentViewModel assessmentviewmodel = GetAssessment(id);

            assessmentviewmodel.AllQuestions = new List<QuestionReferenceViewModel>();
            GetAssessmentData(assessmentviewmodel);
            if (assessmentviewmodel.Questions != null && assessmentviewmodel.Questions.Count >0)
            {
                assessmentviewmodel.QuestionIds = assessmentviewmodel.Questions.Select(q => q.QuestionId).ToArray();
            }
            else
            {
                assessmentviewmodel.QuestionIds = new int [0];
            }
            

            return View(assessmentviewmodel);
        }

        private List<QuestionReferenceViewModel> GetAllQuestions()
        {
            //var urlParams = new List<Tuple<string,string>>();
            //urlParams.Add(new Tuple<string, string>("countOnly", "false"));
            var listQuestions = TestBankApiProxy.Get<List<Question>>(ApiKey, ResourceEndPoint.Question_All);
            var allQuestions = listQuestions.Select(q => new QuestionReferenceViewModel() { QuestionId = Convert.ToInt32(q.Id), Description = q.Description, Sort = q.Sort }).ToList();

            return allQuestions;
        }

        //
        // POST: /Assessments/Edit/5

        [HttpPost]
        public ActionResult Edit(AssessmentViewModel assessmentViewModel)
        {
            if (ModelState.IsValid)
            {
                if (assessmentViewModel != null)
                {
                    assessmentViewModel.Questions = assessmentViewModel.QuestionIds.Select(x => new QuestionReferenceViewModel { QuestionId = x }).ToList();
                    var assessment = TestBankApiProxy.Get<Assessment>(ApiKey, ResourceEndPoint.Assessments_Get, assessmentViewModel.Id);
                    var assessmentUpd = Mapper.Map<AssessmentViewModel, Assessment>(assessmentViewModel);

                    assessment = TestBankApiProxy.Put<Assessment>(ApiKey, assessmentUpd, ResourceEndPoint.Assessments_Put, assessmentViewModel.Id);
                    return RedirectToAction("Index");
                }
            }
            GetAssessmentData(assessmentViewModel);
            return View(assessmentViewModel);
        }

        //
        // GET: /Assessments/Delete/5
 
        public ActionResult Delete(int id)
        {
            AssessmentViewModel assessmentviewmodel = GetAssessment(id);
            return View(assessmentviewmodel);
        }

        //
        // POST: /Assessments/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var assessment = TestBankApiProxy.Delete<Assessment>(ApiKey, ResourceEndPoint.Assessments_Get, id);
            return RedirectToAction("Index");
        }

        private AssessmentViewModel GetAssessment(int id)
        {
            var assessment = TestBankApiProxy.Get<Assessment>(ApiKey, ResourceEndPoint.Assessments_Get, id);
            AssessmentViewModel assessmentviewmodel = null;
            if (assessment != null)
            {
                assessmentviewmodel = Mapper.Map<Assessment, AssessmentViewModel>(assessment);
            }
            return assessmentviewmodel;
        }

        [HttpGet]
        public ActionResult Start(int id)
        {
            AssessmentViewModel assessmentviewmodel = GetAssessment(id);
            return View(assessmentviewmodel);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

TestBank.Web/Views/Assessments/Create.cshtml
@model TestBank.Web.ViewModels.AssessmentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Assessment</legend>

		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TestBank.Web/Views/Assessments/Delete.cshtml
@model TestBank.Web.ViewModels.AssessmentViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Assessment</legend>

    <div class="display-label">TestName</div>
    <div class="display-field">@Model.TestName</div>

    <div class="display-label">Questions</div>
    <div class="display-field">@(Model.Questions == null ? "None" : Model.Questions.Count.ToString())</div>

    <div class="display-label">CreationDate</div>
    <div class="display-field">@String.Format("{0:g}", Model.CreatedDate)</div>

    <div class="display-label">CreatedUser</div>
    <div class="display-field">@Model.CreatedUser</div>

    <div class="display-label">ModifiedDate</div>
    <div class="display-field">@String.Format("{0:g}", Model.ModifiedDate)</div>

    <div class="display-label">ModifiedUser</div>
    <div class="display-field">@Model.ModifiedUser</div>

    <div class="display-label">Link</div>
    <div class="display-field">@Model.Link</div>

    <div class="display-label">ShortLink</div>
    <div class="display-field">@Model.ShortLink</div>

    <div class="display-label">Status</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.Status).ToString()</div>

    <div class="display-label">Enable</div>
    <div class="display-field">@Model.Enable</div>

    <div class="display-label">Duration</div>
    <div class="display-field">@Model.Duration</div>

    <div class="display-label">MaxOptions</div>
    <div class="display-field">@Model.MaxOptions</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

TestBank.Web/Views/Assessments/Details.cshtml
@model TestBank.Web.ViewModels.AssessmentViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <table>
        <tr>
            <td>TestName</td>
            <td>@Model.TestName</td>
        </tr>
        <tr>
            <td>Questions</td>
            <td>@(Model.Questions == null ? "None" : Model.Questions.Count.ToString())</td>
        </tr>
        <tr>
            <td>Link</td>
            <td>@Html.Raw(string.Format("<a href='{0}' target='_blank' >Link</a>", Html.DisplayFor(model => model.Link)))</td>
        </tr>
        <tr>
            <td>ShortLink</td>
            <td>@Html.Raw(string.Format("<a href='{0}' target='_blank' >Short Link</a>", Html.DisplayFor(model => model.ShortLink)))</td>
        </tr>
        <tr>
            <td>Status</td>
            <td>@Html.DisplayTextFor(_ => Model.Status).ToString()</td>
        </tr>
        <tr>
            <td>Enable</td>
            <td>@Model.Enable</td>
        </tr>
        <tr>
            <td>Duration</td>
            <td>@Model.Duration</td>
        </tr>
        <tr>
            <td>Max Options</td>
            <td>@Model.MaxOptions</td>
        </tr>
        <tr>
            <td>Creation Date</td>
            <td>@String.Format("{0:g}", Model.CreatedDate)</td>
        </tr>
        <tr>
            <td>Created User</td>
            <td>@Model.CreatedUser</td>
        </tr>
        <tr>
            <td>Modified Date</td>
            <td>@String.Format("{0:g}", Model.ModifiedDate)</td>
        </tr>
        <tr>
            <td>Modified User</td>
            <td>@Model.ModifiedUser</td>
        </tr>
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TestBank.Web/Views/Assessments/Edit.cshtml
@model TestBank.Web.ViewModels.AssessmentViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Assessment</legend>

        @Html.HiddenFor(model => model.Id)
		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TestBank.Web/Views/Assessments/Index.cshtml
@model IEnumerable<TestBank.Web.ViewModels.AssessmentViewModel>

@{
    ViewBag.Title = "Index";
}

<h3>Assessment list</h3>

<p>
    @Html.ActionLink("New Assessment", "Create")
</p>
<table id="listAssessment">
    <tr>
        <th></th>
        <th>
            Test Name
        </th>
        <th>
            Total Questions
        </th>
        @*<th>
            Link
        </th>
        <th>
            ShortLink
        </th>
        <th>
            Status
        </th>
        <th>
            Enable
        </th>*@
        <th>
            Duration
        </th>
       @* <th>
            MaxOptions
        </th>*@
    </tr>

@foreach (var item in Model) {
    RouteValueDictionary tRVD = new RouteValueDictionary();
    //var dict = new Dictionary<string, string>();
    //dict.Add("testId", item.Id.ToString());
    //tRVD.Add("data", TestBank.Web.Infrastructure.ValueProviders.Crypto.Encrypt(dict));
    tRVD.Add("testId", TestBank.Web.Infrastructure.Encryption.EncryptDecryptQueryString.Encrypt(item.Id.ToString()));
        
    RouteValueDictionary expRVD = new RouteValueDictionary();
    expRVD.Add("testId", item.Id);
    expRVD.Add("output", "excel");
    <tr>
        <td width="15%">
            <a href="@Url.Action("Edit",new { id = item.Id })"><img title="Edit" src="@Url.Content("~/Images/edit-icon.png")" alt="Edit"/></a>
            <a href="@Url.Action("Start", "Answers", tRVD)"><img title="Start Test" src="@Url.Content("~/Images/start.png")" alt="start"/></a>
            <a href="@Url.Action("Results", "Answers", tRVD)"><img title="Results" src="@Url.Content("~/Images/view_detail.png")" alt="results"/></a>
            <a href="@Url.Action("Export", "Answers", expRVD)"><img title="Export to excel" src="@Url.Content("~/Images/excel-icon.png")" alt="xls"/></a>
        </td>
        <td width="60%">
			@item.TestName
        </td>
        <td width="20%">
			@(item.Questions == null ? "None" : item.Questions.Count.ToString())
        </td>
        
       @* <td>
			@item.Link
        </td>
        <td>
			@item.ShortLink
        </td>
        <td>
			@Html.DisplayTextFor(_ => item.Status).ToString()
        </td>
        <td>
			@item.Enable
        </td>*@
        <td>
			@item.Duration min.
        </td>
       @* <td>
			@item.MaxOptions
        </td>*@
    </tr>
}

</table>

TestBank.Web/Views/Assessments/_CreateOrEdit.cshtml
@model TestBank.Web.ViewModels.AssessmentViewModel
@* This partial view defines form fields that will appear when creating and editing entities *@

<div class="MainContent">
    <table>
        <tr>
            <td>@Html.LabelFor(model => model.TestName)
            </td>
            <td>@Html.EditorFor(model => model.TestName)
            </td>
            <td>@Html.ValidationMessageFor(model => model.TestName)
            </td>
        </tr>
        @*<tr>
            <td>@Html.LabelFor(model => model.Link)</td>
            <td>@Html.Raw(string.Format("<a href='{0}' target='_blank' >Links</a>", Html.DisplayFor(model => model.Link)))</td>
            <td>@Html.ValidationMessageFor(model => model.Link)</td>
        </tr>*@
        @*<tr>
            <td>@Html.LabelFor(model => model.ShortLink)</td>
            <td>@Html.Raw(string.Format("<a href='{0}' target='_blank' >ShortLink</a>", Html.DisplayFor(m => m.ShortLink)))</td>
            <td>@Html.ValidationMessageFor(model => model.ShortLink)</td>
        </tr>*@
        <tr>
            <td>@Html.LabelFor(model => model.Enable)</td>
            <td>@Html.EditorFor(model => model.Enable)</td>
            <td>@Html.ValidationMessageFor(model => model.Enable)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Duration)</td>
            <td>@Html.EditorFor(model => model.Duration)</td>
            <td>@Html.ValidationMessageFor(model => model.Duration)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.MaxOptions)</td>
            <td>@Html.EditorFor(model => model.MaxOptions)</td>
            <td>@Html.ValidationMessageFor(model => model.MaxOptions)</td>
        </tr>
        @*<tr>
            <td>@Html.LabelFor(model => model.CreationDate)</td>
            <td>@Html.DisplayFor(model => model.CreationDate)</td>
            <td>@Html.ValidationMessageFor(model => model.CreationDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.CreatedUser)</td>
            <td>@Html.DisplayFor(model => model.CreatedUser)</td>
            <td>@Html.ValidationMessageFor(model => model.CreatedUser)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.ModifiedDate)</td>
            <td>@Html.DisplayFor(model => model.ModifiedDate)</td>
            <td>@Html.ValidationMessageFor(model => model.ModifiedDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.ModifiedUser)</td>
            <td>@Html.DisplayFor(model => model.ModifiedUser)</td>
            <td>@Html.ValidationMessageFor(model => model.ModifiedUser)</td>
        </tr>*@
        <tr>
            <td>@Html.Label("All Questions")</td>
            <td colspan="2">@Html.ListBoxFor(m => m.QuestionIds, new MultiSelectList(Model.AllQuestions, "QuestionId", "Description"), new { size = "10", style = "width:500px" })</td>
        </tr>
        <tr>
            <td></td>
            <td colspan="2">@Html.ValidationMessageFor(model => model.QuestionIds)</td>
        </tr>
    </table>
</div>